language: node_js
node_js:
  - 9.10.1
services:
  - neo4j
  - redis-server
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
    - 167.99.98.101 # droplet IP
branches:
  only:
    - master
    - Development
env:
  global:
    - REMOTE_APP_DIR=/var/www/cooper.mx/
    - REMOTE_USER=deploy
    - REMOTE_HOST=167.99.98.101 # droplet IP
    - PORT=80
before_install:
  - openssl aes-256-cbc -K $encrypted_7c1afc1ba21b_key -iv $encrypted_7c1afc1ba21b_iv -in deploy.enc -out deploy -d
install:
  - npm install
before_script:
  - chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
  - npm run build
  - npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
