language: node_js
node_js:
- 9.10.1
services:
- neo4j
- redis-server
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 167.99.98.101
branches:
  only:
  - master
  - Development
  - Testing
env:
  global:
  - REMOTE_APP_DIR=/var/www/cooper.mx/
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.99.98.101
  - PORT=80
  matrix:
  - secure: UcVbaknqY0TAMoI7OoyXHd4dqMWr74PTnae1Z1H59C1PSXknJuKyf/nl+7wmE3r1qeHlYy3uBF6L/p8xHazNGkdUHPq8lioa/QBhZgc9855R9SBgeB0KVVPu1Jpcek7EWh07cVxZmxNdrLAW6wTFVIUQr4G2Qp23tTvwgoBlIJjBatPTqwwdfCCQkiCjTVOaBkCcSgJKuSnTYICYtCyfrrODUtX9jzs1bLw/aw3f9yoEySNgKErFdeilCQa9siwfa/CALEt0IG1cIqoyyZZhz3vZteCqDkXBQiC4w52YcWCRDyNFqslia/+vDsx60zbIYolVsVxwwy5xsLOfvmlFvCDBoubn8DkAB4+M3ftv9ys24mC2j5plGTfZU6uD7bTRdI12q35FIX4iV9Ig0lS7MAyodtXkAttTA2JFVbd4d5x9QYNibHbkZHJ38Yj25rk6T/xVvrU7PAlxQh+FM/pSFPXpkXZj1gJ0nrRYmU2HOhVyc/LzI8AVk3GH4qG7UmtnNp6UkFZV+VnCP6vh7JuQh+IaxW20arIUvPEFAHNexqO9PasuCkLLfUPQdd4JpzwH5IOOTazCyLIcd4uTWNBRlbOY13NvVBDPIukBQr+d5ujHPO05HF+NsqXp5W7B2xVkNqcE4R/AtcU1VhuhEVW3crYUh4jd4EA297xGoNYZa/0=
  - secure: zP7hWuD5sw7OMha+vl72x3jkrd9BUpw8Xo3NKzy4VviTKd315GKYGZHZbRz9+mxOVraI04ebF0o8dxs4hUYFvMY8GtDZhq65NE/5lS0slJaayWOqNFYO11UD4tjoPlwyCy0t48BMjNIEp2ucJi+10gCMDAlp74mJdKZiQP399ap8HobBuuzuY5MU1rCjVYYVKzba4zqpqqKhX98wSWB9tix7fnYrQq+o67tankm8AUAA+qrr6+GXaSReL4Y7ET2k33ZK8mqZC5mkvae0OX4k4U0btAkZ6b6HJ2yUa+7hYN+rkz2FVasdIPhxfIHTdKCASqx/sp2GUk126Re6U+uBQv3gbG+/lzBgGyrucKD0OjYT5q01NLHxTYZWO9iMYlt81lYN8+AV1j2/qJMBfK6AnQZHC2ob2WAqnAeHf1qsHcGKcak+c2ro2vbeDTNpctfH2f9ML19uIjjgtUZXvGRJDQn6CFbWohFBUX5g/UBJyOa6p+KEcDGqsE9ZvbOOsM2VEz1p8WvQZwzDJsLV3whluXSq0/t4kEsJ7EmEcVGAfvU1AL7mo7KIccrJpkKTEfDzht64a55YIf0NsFxoyZDDjWa+lK1utGt/94fIFxxWBYdzH4Dn1wjmD+fFi5dSsvhlqNOyMb2Hmaaioyvf8UethWmKn2zDQtG5PyQSWAn4xWw=
  - secure: 0QAs5NJAC01iNPlIUjKwKBmOHPStuCmMj897wm/u2x0CRzlPYIHMHjepCdj569MU7wCVv5K1vCNd5wBs4ifdIz5UfTtiToEqnhn5yWFWrteUxeYKuXy4kOhX35ZoJzXi9kPIsr+65GXiGlZ6Zkx9x4T+K4X/ACvcv/1cYZCIcZJDGvNaZvgl9eN56rP1jNljx1+zYFTc0n+qAuLSh3G/+jV1wNVtuJI9WjtZ8GVnh2zf8ALuyhL20GuD8XHoC/qxe+GTTXXB5BPkPrbhM3KpP1D+iWcAtyPoZRBIift2wbASnyadJFZ2GdivCijSPqIU1p/BOkKIG0/1CdSLkDubzs14/i2E6+ogOmbX4zAn7WHgugx3OUVCbvyDJ8p3Gzlh0nFzlmEQJ2FBRumqya+dtoB/bFvBoBxxIj1e3yliIEsKV3zjzG/KvBFf5I+0iIM584VZO/PJpVufCDIT/MnwlQ056FXGhtmqdVvJl6F6yhCIOoTuHA/BHI410f0hmJNnvL1wg7QlY1zy/qNMAJVCr7B4G1DPSgHt3a9ZTbdUTukNve0s8zq/DF1u4DCb4eafKaqFAjnJ1G6B7LEWT1H9XA1giKiE7WzwxVznISEUhOSyB6ZqS8GAKOBcaN87jbtInZ/nu9MTy6atKN2+FUOAQf7OE3Y8ZFhmT/NcD+F3zwo=
  - secure: 1BTY9GAVmBlPwk96po4EkOIOHACzj+Q6JmOOFiq8q/5shaSvQBcnA3b27CgRebwfioQYtmsrMNYJLeVy1HIG45kAnfDqyRFR88ylHbkiw8XomEW4M+bcZI4JRIKFkH/Df3x+dEzb+85Jm2zlbKEtBDf6pAepncUYMqY5BBb0zfhJ0HnMiwTFDW76iMLr6cb7+S6xGRCXJr16d+geLanE/86I2BEn9Dd/fbYqsSrl4rpKFSFBXGyVuaX5FAnQs6MvHg1NjQRIlsTmbPkSti7N796Q9fekqi6e9jdDXGvp8NLC5/rzNA9xBowiwxK8ExMdliwR9Z74YDVAM0epKaXUek9UJlLcRO9x1Px2h3V9A8I8rX2NyI6jMHAchwhxF4KJD3Z8aiH/koNsD+ho/C6lKO4Y8X0JlxMHF4cOLow5YFYVrhw4E0bEzjbnfLHCeVY/3oz83iataPitmCpOpaKNyWh1K7xqjQBtZqiQeCYAxp1Pw2xars20BA7goq+h/k60YUUY5pP+v84ZkYNv3ERX1CRKgOrGFF9J/uyxyNTncLeHACl5f/x59E5elYRJs1imcRJssHFlIYgTDQplhXKcRHUyRGfIcGlsEX2YnhLmYzCfLJFn0X7yN+0GfYccC0m8HDpNZAbc3AA3ShPPh8gGH9xwcAoMpMt8Qll26Xz6NP8=
  - secure: a/2r2BAWhgPMim0JyZTM6QU18JsoRzDQbWaVHqx6ZuDhX6LuIfY148PYKe3rGgi7OuFYnVz6TQtZv6hsKWi6W0DTENXygIX3zEyx+qn1zF7wzNIg5emiR/lI8+qhkIQkuGkdUxMr1fkoyh2DZ1FgV1O+Hp5ypXCDA2u20DAFHFCB8HeindXcSPOZx6I3qzGcOOg0Wjv062+TjfAUTZoVQERf2IpiXmN9EFfI78coqme3CATcdOr9XanFruA/6W7cuSS8FNyDYHlQdmYTIo76ULO2CfRZfot9VPjMo2GEXNsiHF377DpyXUJGKo+/AdC6MxrIfOfpkuFAwqwPPx5ECEOlBWuOOO7hBKjuPiUJUk8EtQxgC1v38TCjvQEOfaqK+gmkyPGtYyFQXWK6fp7CvGUeoQtl042MrTThDe7SIXyCwLfCDFk1f6/AmVI/POfyI+ueetEphLHO9949ssUJXZtdC59mtqoyL9KKtdc5gnC8TE7fIg0PTq/9tV2pJk/P8kARR+QXdUUs7gTR0ht2NeSsJqiQqkjwXj6DZ/40lzaTs/6FfaHtvPVebnr2cMONSJ7dhsKy6jK176jwsOYSB2sDMtlfajUwuNfUqszyPOcJvn+Li95Y1kjbuaxi4RUBMJ5snWiwkMnb7emMwgQd6Wtxib70V9MzcdHISrtcWqs=
  - secure: 1iMwVgDNYU4nxkF4uDkGCPfD1Vgk+ctf9tcaBsp98oWU9KS4mUcLq4Br62XEgghj98mJmLnOe1RHRubuWud6PedQDZytgfm4rC+1TYL9km6emFJd/sXQcxv2uRLBh8mjqP0cjLbDi3t+PogApU3Zen1KgHytGkmgSwAmYNJSdO6sVMQ10PUpXfzn3KayBdxBu+nGLdejxruUalA/TUWbbh/g16JgN7efkJiMDMpabqlZg5Ielys2qSEs2OpzIKdCPZP/9Wm8GsKqb9Sn6NlY0elKXUSgCH/Uz6qInL3tXyk/uLc93+X9QthPGkrB4J54dWGRWtyffoiZYOIMVeLiAcH/YkTHXJu3gm43FHt/qzRRnCmveCvlaVKGbCfvScT3JRbBsqA0FNLv1Ks5IT5VWpG78WaRG8vPn68BDuQJqkal4rTwPBKUJUMzUFu4uy/V6TjUugPjVjeZpml6Xm+ozdyoPwI86y3/zrsQXiNEaNIwRcFZplk47J55PVUBuYd3afTDPn+K8Co/nw09NoJ/7m7ck6Wz2j+/1P6bnzEjE928rDmFPi3boRImKavgqXsnId5nbpRtjf3TiNvUUz6y5KEbmnkGhcgcAJLfX7ZOfC42yjzOo3HwUwLRrNs/PFxvPMFyBpXIZAv/EhmgIT4QIMau7tqK/8wCqf+WM+u0BaQ=
  - secure: 21RMLMMODy+VI4YQ5HCAT/p5ghssrSKH/hV9j/enlFsyceOztY1T4bmavDEsvTSkikuEV8itivvtdZPePzt/AymMSOv/3o5Nd4lNgWNzGtNjNN4EqIHWbnMi+AX9JSot/TzSA/7iYHb5eeOHlsxo22IILRN7UXf5YDfx1s/AUcdBvKSvUFnCfN0ZKjh25GHbuVOPfw1nJeI4gQbS+Qu6PIzojiwgeHN26hvJi0rfSQPYVvazRXwlQdxvys3FocNrkOOnoJklmr25MHbqRtXWxmh+MBqip0jn6/gZ0CnUZ4uaDfb2Yjap1TXGtt/ykNksfZjdtEGA1qbzvBhw4Wj49dbpe+W3rcEQY6dEJz5V4BEt2xQ1DW8goCTgHJYKnuMbEu2m4G00lytj0tBElr44JFteQlTt+ZkmdppnYRarQP30WKf3HMPOpFk7k+jwEAbYAtaeDw8AGfZZ3ghcZuObxgOXobGI8X0dOmK/Ie9RlYPxCyTPKzwpRZ9E3xmuEMo7Dssv41ASUekUmVij+tJwGKOFhtEB1cT5G5TVBlmrzphlqi5L+u8gNQNwqDFTNeDEN53w0f+8rM8tCjRZ0DMuazz29rLE41YwfoKTaVsy6cCN1ufG9Cf33drMGlYpVYpZqE+IGKf1Uaa+gdinNs3dS/Pj1Q9D1iYOv8mu0Gpxeuo=
before_install:
- openssl aes-256-cbc -K $encrypted_7c1afc1ba21b_key -iv $encrypted_7c1afc1ba21b_iv
  -in deploy.enc -out deploy -d
install:
- npm install
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
