language: node_js
node_js:
- 9.10.1
jdk:
- oraclejdk7  # needed for local Neo4j 2.0+
services:
- redis-server
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 167.99.98.101
branches:
  only:
  - master
  - Development
  - Testing
env:
  global:
  - REMOTE_APP_DIR=/var/www/cooper.mx/
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.99.98.101
  - PORT=80
  - NEO4J_VERSION="2.1.5"
before_install:
- openssl aes-256-cbc -K $encrypted_7c1afc1ba21b_key -iv $encrypted_7c1afc1ba21b_iv
  -in deploy.enc -out deploy -d
# install Neo4j locally:
- wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
- tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
- neo4j-community-$NEO4J_VERSION/bin/neo4j start
install:
- npm install
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
